-- Logros del club y refuerzo de privacidad del centro de ayuda.
-- Ejecuta este archivo una vez en Supabase > SQL Editor.

begin;

create or replace function public.current_user_is_club_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'superadmin')
  );
$$;
revoke all on function public.current_user_is_club_admin() from public;
grant execute on function public.current_user_is_club_admin() to authenticated;

create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 70),
  description text not null default '' check (char_length(description) <= 240),
  tier text not null check (tier in ('bronze', 'silver', 'gold', 'platinum')),
  icon text not null default '' check (char_length(icon) <= 12),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.achievement_awards (
  id bigint generated by default as identity primary key,
  achievement_id bigint not null references public.achievements(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  awarded_by uuid not null references public.profiles(id) on delete restrict,
  awarded_at timestamptz not null default now(),
  unique (achievement_id, user_id)
);

alter table public.achievements enable row level security;
alter table public.achievement_awards enable row level security;

drop policy if exists "members read achievements" on public.achievements;
create policy "members read achievements" on public.achievements
  for select to authenticated using (true);

drop policy if exists "admins create achievements" on public.achievements;
create policy "admins create achievements" on public.achievements
  for insert to authenticated with check (created_by = auth.uid() and public.current_user_is_club_admin());

drop policy if exists "admins update achievements" on public.achievements;
create policy "admins update achievements" on public.achievements
  for update to authenticated using (public.current_user_is_club_admin())
  with check (public.current_user_is_club_admin());

drop policy if exists "admins delete achievements" on public.achievements;
create policy "admins delete achievements" on public.achievements
  for delete to authenticated using (public.current_user_is_club_admin());

drop policy if exists "members read achievement awards" on public.achievement_awards;
create policy "members read achievement awards" on public.achievement_awards
  for select to authenticated using (true);

drop policy if exists "admins create achievement awards" on public.achievement_awards;
create policy "admins create achievement awards" on public.achievement_awards
  for insert to authenticated with check (awarded_by = auth.uid() and public.current_user_is_club_admin());

drop policy if exists "admins delete achievement awards" on public.achievement_awards;
create policy "admins delete achievement awards" on public.achievement_awards
  for delete to authenticated using (public.current_user_is_club_admin());

create or replace function public.create_achievement_with_awards(
  new_name text,
  new_description text,
  new_tier text,
  new_icon text,
  target_user_ids uuid[]
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  created_id bigint;
begin
  if not public.current_user_is_club_admin() then raise exception 'No tienes permiso para crear logros.'; end if;
  if char_length(trim(new_name)) not between 2 and 70 then raise exception 'El nombre del logro no es válido.'; end if;
  if char_length(coalesce(new_description, '')) > 240 then raise exception 'La descripción es demasiado larga.'; end if;
  if new_tier not in ('bronze', 'silver', 'gold', 'platinum') then raise exception 'El rango no es válido.'; end if;
  if cardinality(coalesce(target_user_ids, '{}'::uuid[])) = 0 then raise exception 'Selecciona al menos un miembro.'; end if;

  insert into public.achievements (name, description, tier, icon, created_by)
  values (trim(new_name), trim(coalesce(new_description, '')), new_tier, left(trim(coalesce(new_icon, '')), 12), auth.uid())
  returning id into created_id;

  insert into public.achievement_awards (achievement_id, user_id, awarded_by)
  select created_id, profile.id, auth.uid()
  from public.profiles profile
  where profile.id = any(target_user_ids) and not profile.is_hidden;

  if not exists (select 1 from public.achievement_awards where achievement_id = created_id) then
    raise exception 'No se encontró ningún miembro válido para asignar el logro.';
  end if;
  return created_id;
end;
$$;
revoke all on function public.create_achievement_with_awards(text, text, text, text, uuid[]) from public;
grant execute on function public.create_achievement_with_awards(text, text, text, text, uuid[]) to authenticated;

create or replace function public.set_achievement_awards(target_achievement_id bigint, target_user_ids uuid[])
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.current_user_is_club_admin() then raise exception 'No tienes permiso para asignar logros.'; end if;
  if not exists (select 1 from public.achievements where id = target_achievement_id) then raise exception 'El logro no existe.'; end if;

  delete from public.achievement_awards where achievement_id = target_achievement_id;
  insert into public.achievement_awards (achievement_id, user_id, awarded_by)
  select target_achievement_id, profile.id, auth.uid()
  from public.profiles profile
  where profile.id = any(coalesce(target_user_ids, '{}'::uuid[])) and not profile.is_hidden;
end;
$$;
revoke all on function public.set_achievement_awards(bigint, uuid[]) from public;
grant execute on function public.set_achievement_awards(bigint, uuid[]) to authenticated;

-- Defensa en base de datos: solo el creador y los administradores leen cada ticket.
drop policy if exists "members read own help requests" on public.help_requests;
create policy "members read own help requests" on public.help_requests
  for select to authenticated using (user_id = auth.uid() or public.current_user_is_help_admin());

drop policy if exists "participants read help messages" on public.help_messages;
create policy "participants read help messages" on public.help_messages
  for select to authenticated using (
    public.current_user_is_help_admin()
    or exists (select 1 from public.help_requests where id = request_id and user_id = auth.uid())
  );

create index if not exists achievements_created_at_idx on public.achievements(created_at desc);
create index if not exists achievement_awards_user_idx on public.achievement_awards(user_id, awarded_at desc);
create index if not exists achievement_awards_achievement_idx on public.achievement_awards(achievement_id, awarded_at desc);

do $$ begin
  alter publication supabase_realtime add table public.achievements;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.achievement_awards;
exception when duplicate_object then null;
end $$;

commit;
