-- Centro de ayuda independiente para usuarios y administradores.
-- Ejecuta este archivo una vez en Supabase > SQL Editor.

create table if not exists public.help_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  request_type text not null check (request_type in ('help', 'suggestion', 'complaint')),
  status text not null default 'new' check (status in ('new', 'in_progress', 'answered')),
  handled_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.help_messages (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.help_requests(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.help_requests enable row level security;
alter table public.help_messages enable row level security;

create or replace function public.current_user_is_help_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'superadmin')
  );
$$;
revoke all on function public.current_user_is_help_admin() from public;
grant execute on function public.current_user_is_help_admin() to authenticated;

drop policy if exists "members read own help requests" on public.help_requests;
create policy "members read own help requests" on public.help_requests
  for select to authenticated using (user_id = auth.uid() or public.current_user_is_help_admin());

drop policy if exists "members create own help requests" on public.help_requests;
create policy "members create own help requests" on public.help_requests
  for insert to authenticated with check (user_id = auth.uid() and status = 'new' and handled_by is null);

drop policy if exists "admins update help requests" on public.help_requests;
create policy "admins update help requests" on public.help_requests
  for update to authenticated using (public.current_user_is_help_admin())
  with check (public.current_user_is_help_admin());

drop policy if exists "participants read help messages" on public.help_messages;
create policy "participants read help messages" on public.help_messages
  for select to authenticated using (
    public.current_user_is_help_admin()
    or exists (select 1 from public.help_requests where id = request_id and user_id = auth.uid())
  );

drop policy if exists "participants create help messages" on public.help_messages;
create policy "participants create help messages" on public.help_messages
  for insert to authenticated with check (
    sender_id = auth.uid() and (
      public.current_user_is_help_admin()
      or exists (select 1 from public.help_requests where id = request_id and user_id = auth.uid())
    )
  );

create or replace function public.sync_help_request_from_message()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  sender_is_admin boolean;
begin
  select role in ('admin', 'superadmin') into sender_is_admin
  from public.profiles where id = new.sender_id;

  update public.help_requests
  set status = case when sender_is_admin then 'answered' else 'new' end,
      handled_by = case when sender_is_admin then new.sender_id else null end,
      updated_at = now()
  where id = new.request_id;
  return new;
end;
$$;

drop trigger if exists sync_help_request_from_message on public.help_messages;
create trigger sync_help_request_from_message
  after insert on public.help_messages
  for each row execute procedure public.sync_help_request_from_message();

create or replace function public.create_help_request(new_type text, initial_body text)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  created_id bigint;
begin
  if auth.uid() is null then raise exception 'Sesión no válida.'; end if;
  if new_type not in ('help', 'suggestion', 'complaint') then raise exception 'Motivo no válido.'; end if;
  if char_length(trim(initial_body)) not between 1 and 2000 then raise exception 'El mensaje no es válido.'; end if;
  insert into public.help_requests (user_id, request_type)
  values (auth.uid(), new_type) returning id into created_id;
  insert into public.help_messages (request_id, sender_id, body)
  values (created_id, auth.uid(), trim(initial_body));
  return created_id;
end;
$$;
revoke all on function public.create_help_request(text, text) from public;
grant execute on function public.create_help_request(text, text) to authenticated;

create index if not exists help_requests_user_updated_idx on public.help_requests(user_id, updated_at desc);
create index if not exists help_requests_status_updated_idx on public.help_requests(status, updated_at desc);
create index if not exists help_messages_request_created_idx on public.help_messages(request_id, created_at);

do $$
begin
  alter publication supabase_realtime add table public.help_requests;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.help_messages;
exception when duplicate_object then null;
end $$;
