-- Ejecuta este archivo completo en Supabase > SQL Editor.
-- Después crea las nueve cuentas indicadas en README.md desde Authentication > Users.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_id smallint unique not null check (legacy_id between 1 and 32767),
  username text unique not null,
  display_name text not null,
  nickname text not null default 'The Big Boy',
  bio text not null default '',
  tags text[] not null default '{}',
  avatar_url text,
  role text not null default 'member' check (role in ('superadmin', 'admin', 'member')),
  is_hidden boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists is_hidden boolean not null default false;
alter table public.profiles drop constraint if exists profiles_legacy_id_check;
alter table public.profiles add constraint profiles_legacy_id_check check (legacy_id between 1 and 32767);
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('superadmin', 'admin', 'member'));

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legacy_id smallint not null references public.profiles(legacy_id),
  body text not null check (char_length(body) between 1 and 1200),
  created_at timestamptz not null default now()
);

alter table public.messages add column if not exists attachment_url text;
alter table public.messages add column if not exists attachment_name text;
alter table public.messages add column if not exists attachment_type text;
alter table public.messages add column if not exists attachment_size bigint;
alter table public.messages drop constraint if exists messages_body_check;
alter table public.messages add constraint messages_body_check check (
  char_length(body) <= 1200 and (char_length(trim(body)) > 0 or attachment_url is not null)
);

create table if not exists public.moments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legacy_id smallint not null references public.profiles(legacy_id),
  caption text not null default '' check (char_length(caption) <= 300),
  media_url text not null,
  media_type text not null check (media_type in ('image', 'video')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create table if not exists public.profile_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legacy_id smallint not null references public.profiles(legacy_id),
  caption text not null default '' check (char_length(caption) <= 300),
  media_url text not null,
  media_type text not null check (media_type in ('image', 'video')),
  created_at timestamptz not null default now()
);

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1200),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

create table if not exists public.group_events (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 80),
  description text not null default '' check (char_length(description) <= 500),
  starts_at timestamptz not null,
  ends_at timestamptz,
  location text not null default '' check (char_length(location) <= 120),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at)
);

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.moments enable row level security;
alter table public.profile_posts enable row level security;
alter table public.private_messages enable row level security;
alter table public.group_events enable row level security;
alter table public.site_settings enable row level security;

create or replace function public.current_user_can_manage()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and (role = 'superadmin' or (role = 'admin' and username = 'kike'))
  );
$$;

revoke all on function public.current_user_can_manage() from public;
grant execute on function public.current_user_can_manage() to authenticated;

create or replace function public.current_user_is_superadmin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'superadmin' and is_hidden
  );
$$;

revoke all on function public.current_user_is_superadmin() from public;
grant execute on function public.current_user_is_superadmin() to authenticated;

create or replace function public.protect_profile_identity()
returns trigger
language plpgsql
as $$
begin
  if not public.current_user_is_superadmin() and (
    new.id <> old.id
    or new.legacy_id <> old.legacy_id
    or new.username <> old.username
    or new.role <> old.role
    or new.is_hidden <> old.is_hidden
  ) then
    raise exception 'No puedes modificar la identidad o el rol de tu cuenta';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_identity on public.profiles;
create trigger protect_profile_identity
  before update on public.profiles
  for each row execute procedure public.protect_profile_identity();

drop policy if exists "members read profiles" on public.profiles;
create policy "members read profiles" on public.profiles
  for select to authenticated using (not is_hidden or auth.uid() = id);

drop policy if exists "members update own profile" on public.profiles;
create policy "members update own profile" on public.profiles
  for update to authenticated
  using (auth.uid() = id or public.current_user_is_superadmin())
  with check (auth.uid() = id or public.current_user_is_superadmin());

drop policy if exists "members read messages" on public.messages;
create policy "members read messages" on public.messages
  for select to authenticated using (true);

drop policy if exists "members send as themselves" on public.messages;
create policy "members send as themselves" on public.messages
  for insert to authenticated
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.legacy_id = messages.legacy_id
    )
  );

drop policy if exists "superadmin deletes messages" on public.messages;
create policy "superadmin deletes messages" on public.messages
  for delete to authenticated using (public.current_user_is_superadmin());

drop policy if exists "members read active moments" on public.moments;
create policy "members read active moments" on public.moments
  for select to authenticated using (expires_at > now());

drop policy if exists "members create own moments" on public.moments;
create policy "members create own moments" on public.moments
  for insert to authenticated with check (
    auth.uid() = user_id and expires_at <= now() + interval '24 hours 5 minutes'
    and exists (select 1 from public.profiles where id = auth.uid() and legacy_id = moments.legacy_id)
  );

drop policy if exists "members delete own moments" on public.moments;
create policy "members delete own moments" on public.moments
  for delete to authenticated using (auth.uid() = user_id or public.current_user_is_superadmin());

drop policy if exists "members read profile posts" on public.profile_posts;
create policy "members read profile posts" on public.profile_posts
  for select to authenticated using (true);

drop policy if exists "members create own profile posts" on public.profile_posts;
create policy "members create own profile posts" on public.profile_posts
  for insert to authenticated with check (
    auth.uid() = user_id
    and exists (select 1 from public.profiles where id = auth.uid() and legacy_id = profile_posts.legacy_id)
  );

drop policy if exists "members delete own profile posts" on public.profile_posts;
create policy "members delete own profile posts" on public.profile_posts
  for delete to authenticated using (auth.uid() = user_id or public.current_user_is_superadmin());

drop policy if exists "participants read private messages" on public.private_messages;
create policy "participants read private messages" on public.private_messages
  for select to authenticated using (
    auth.uid() = sender_id or auth.uid() = recipient_id or public.current_user_is_superadmin()
  );

drop policy if exists "members send private messages" on public.private_messages;
create policy "members send private messages" on public.private_messages
  for insert to authenticated with check (
    auth.uid() = sender_id and sender_id <> recipient_id
    and exists (select 1 from public.profiles where id = recipient_id)
  );

drop policy if exists "superadmin deletes private messages" on public.private_messages;
create policy "superadmin deletes private messages" on public.private_messages
  for delete to authenticated using (public.current_user_is_superadmin());

drop policy if exists "members read group events" on public.group_events;
create policy "members read group events" on public.group_events
  for select to authenticated using (true);

drop policy if exists "kike creates group events" on public.group_events;
create policy "kike creates group events" on public.group_events
  for insert to authenticated with check (
    auth.uid() = created_by and public.current_user_can_manage()
  );

drop policy if exists "kike updates group events" on public.group_events;
create policy "kike updates group events" on public.group_events
  for update to authenticated using (public.current_user_can_manage())
  with check (public.current_user_can_manage());

drop policy if exists "kike deletes group events" on public.group_events;
create policy "kike deletes group events" on public.group_events
  for delete to authenticated using (public.current_user_can_manage());

drop policy if exists "members read site settings" on public.site_settings;
create policy "members read site settings" on public.site_settings
  for select to authenticated using (true);

drop policy if exists "kike creates site settings" on public.site_settings;
create policy "kike creates site settings" on public.site_settings
  for insert to authenticated with check (
    updated_by = auth.uid() and public.current_user_can_manage()
  );

drop policy if exists "kike updates site settings" on public.site_settings;
create policy "kike updates site settings" on public.site_settings
  for update to authenticated using (public.current_user_can_manage())
  with check (updated_by = auth.uid() and public.current_user_can_manage());

drop policy if exists "kike deletes site settings" on public.site_settings;
create policy "kike deletes site settings" on public.site_settings
  for delete to authenticated using (public.current_user_can_manage());

create index if not exists messages_created_at_idx on public.messages(created_at);
create index if not exists moments_expires_at_idx on public.moments(expires_at);
create index if not exists profile_posts_user_created_idx on public.profile_posts(legacy_id, created_at desc);
create index if not exists private_messages_participants_idx on public.private_messages(sender_id, recipient_id, created_at);
create index if not exists group_events_starts_at_idx on public.group_events(starts_at);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 3145728, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public avatar viewing" on storage.objects;
create policy "public avatar viewing" on storage.objects
  for select using (bucket_id = 'avatars');

drop policy if exists "members upload own avatar" on storage.objects;
create policy "members upload own avatar" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'avatars'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.current_user_is_superadmin())
  );

drop policy if exists "members update own avatar" on storage.objects;
create policy "members update own avatar" on storage.objects
  for update to authenticated
  using (
    bucket_id = 'avatars'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.current_user_is_superadmin())
  )
  with check (
    bucket_id = 'avatars'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.current_user_is_superadmin())
  );

drop policy if exists "members delete own avatar" on storage.objects;
create policy "members delete own avatar" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'avatars'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.current_user_is_superadmin())
  );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'group-media', 'group-media', true, 15728640,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm',
        'application/pdf', 'text/plain', 'application/zip',
        'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public group media viewing" on storage.objects;
create policy "public group media viewing" on storage.objects
  for select using (bucket_id = 'group-media');

drop policy if exists "members upload own group media" on storage.objects;
create policy "members upload own group media" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'group-media' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "members update own group media" on storage.objects;
create policy "members update own group media" on storage.objects
  for update to authenticated
  using (bucket_id = 'group-media' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'group-media' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "members delete own group media" on storage.objects;
create policy "members delete own group media" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'group-media'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.current_user_is_superadmin())
  );

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.moments;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.profile_posts;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.private_messages;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.group_events;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.site_settings;
exception
  when duplicate_object then null;
end $$;

-- Vincula automáticamente las cuentas creadas desde el panel con los perfiles.
create or replace function public.handle_new_big_boy()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  uname text := split_part(new.email, '@', 1);
  legacy smallint;
  visible_name text;
  member_role text := 'member';
begin
  legacy := case uname
    when 'kike' then 1 when 'lizzy' then 2 when 'raul' then 3
    when 'mario' then 4 when 'miguelangel' then 5 when 'almudena' then 6
    when 'carlos' then 7 when 'albertovelasco' then 8 when 'caonaboalbero' then 9
  end;
  if legacy is null then
    select (coalesce(max(legacy_id), 9) + 1)::smallint into legacy from public.profiles;
  end if;
  visible_name := case uname
    when 'kike' then 'Kike' when 'lizzy' then 'Lizzy' when 'raul' then 'Raúl'
    when 'mario' then 'Mario' when 'miguelangel' then 'Miguel Ángel'
    when 'almudena' then 'Almudena' when 'carlos' then 'Carlos'
    when 'albertovelasco' then 'Alberto Velasco' when 'caonaboalbero' then 'Caonabo Albero'
  end;
  visible_name := coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), visible_name, initcap(uname));
  if uname = 'kike' then member_role := 'admin'; end if;
  insert into public.profiles (id, legacy_id, username, display_name, nickname, bio, tags, role, is_hidden)
  values (new.id, legacy, uname, visible_name, 'The Big Boy', 'Miembro de The Big Boy Rules.',
    array['Comunidad', 'Momentos', 'Grupo'], member_role, false)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_big_boy();
