-- Ejecutar una vez en Supabase SQL Editor.
alter table public.moments add column if not exists mentioned_user_id uuid references public.profiles(id) on delete set null;
alter table public.profile_posts add column if not exists mentioned_user_id uuid references public.profiles(id) on delete set null;
create table if not exists public.moment_views (
  id bigint generated by default as identity primary key,
  moment_id bigint not null references public.moments(id) on delete cascade,
  viewer_id uuid not null references auth.users(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  unique (moment_id, viewer_id)
);

create table if not exists public.media_replies (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  moment_id bigint references public.moments(id) on delete cascade,
  profile_post_id bigint references public.profile_posts(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 600),
  created_at timestamptz not null default now(),
  check ((moment_id is not null)::int + (profile_post_id is not null)::int = 1)
);

alter table public.moment_views enable row level security;
alter table public.media_replies enable row level security;

create policy "members register moment views" on public.moment_views
  for insert to authenticated with check (viewer_id = auth.uid());
create policy "members refresh own moment view" on public.moment_views
  for update to authenticated using (viewer_id = auth.uid()) with check (viewer_id = auth.uid());
create policy "owners read moment viewers" on public.moment_views
  for select to authenticated using (
    viewer_id = auth.uid() or exists (select 1 from public.moments m where m.id = moment_id and m.user_id = auth.uid())
  );

create policy "members create media replies" on public.media_replies
  for insert to authenticated with check (user_id = auth.uid());
create policy "participants read media replies" on public.media_replies
  for select to authenticated using (
    user_id = auth.uid()
    or exists (select 1 from public.moments m where m.id = moment_id and m.user_id = auth.uid())
    or exists (select 1 from public.profile_posts p where p.id = profile_post_id and p.user_id = auth.uid())
  );
create policy "members delete own replies" on public.media_replies
  for delete to authenticated using (user_id = auth.uid() or public.current_user_can_manage());

create index if not exists moment_views_moment_time_idx on public.moment_views(moment_id, viewed_at desc);
create index if not exists media_replies_moment_time_idx on public.media_replies(moment_id, created_at desc) where moment_id is not null;
create index if not exists media_replies_post_time_idx on public.media_replies(profile_post_id, created_at desc) where profile_post_id is not null;
create index if not exists media_likes_user_idx on public.media_likes(user_id);
create index if not exists moments_created_at_idx on public.moments(created_at desc);
create index if not exists profile_posts_created_at_idx on public.profile_posts(created_at desc);

-- Permite originales de alta resolución de hasta 30 MB.
update storage.buckets set file_size_limit = 31457280 where id = 'group-media';

do $$ begin
  alter publication supabase_realtime add table public.media_replies;
exception when duplicate_object then null;
end $$;
