-- Ejecuta este archivo completo en Supabase > SQL Editor.
-- Después crea las nueve cuentas indicadas en README.md desde Authentication > Users.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_id smallint unique not null check (legacy_id between 1 and 9),
  username text unique not null,
  display_name text not null,
  nickname text not null default 'The Big Boy',
  bio text not null default '',
  tags text[] not null default '{}',
  avatar_url text,
  role text not null default 'member' check (role in ('admin', 'member')),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legacy_id smallint not null references public.profiles(legacy_id),
  body text not null check (char_length(body) between 1 and 1200),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

create or replace function public.protect_profile_identity()
returns trigger
language plpgsql
as $$
begin
  if new.id <> old.id
    or new.legacy_id <> old.legacy_id
    or new.username <> old.username
    or new.role <> old.role then
    raise exception 'No puedes modificar la identidad o el rol de tu cuenta';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_identity on public.profiles;
create trigger protect_profile_identity
  before update on public.profiles
  for each row execute procedure public.protect_profile_identity();

drop policy if exists "members read profiles" on public.profiles;
create policy "members read profiles" on public.profiles
  for select to authenticated using (true);

drop policy if exists "members update own profile" on public.profiles;
create policy "members update own profile" on public.profiles
  for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "members read messages" on public.messages;
create policy "members read messages" on public.messages
  for select to authenticated using (true);

drop policy if exists "members send as themselves" on public.messages;
create policy "members send as themselves" on public.messages
  for insert to authenticated
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.legacy_id = messages.legacy_id
    )
  );

create index if not exists messages_created_at_idx on public.messages(created_at);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 3145728, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public avatar viewing" on storage.objects;
create policy "public avatar viewing" on storage.objects
  for select using (bucket_id = 'avatars');

drop policy if exists "members upload own avatar" on storage.objects;
create policy "members upload own avatar" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "members update own avatar" on storage.objects;
create policy "members update own avatar" on storage.objects
  for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;

-- Vincula automáticamente las cuentas creadas desde el panel con los perfiles.
create or replace function public.handle_new_big_boy()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  uname text := split_part(new.email, '@', 1);
  legacy smallint;
  visible_name text;
  member_role text := 'member';
begin
  legacy := case uname
    when 'kike' then 1 when 'lizzy' then 2 when 'raul' then 3
    when 'mario' then 4 when 'miguelangel' then 5 when 'almudena' then 6
    when 'carlos' then 7 when 'albertovelasco' then 8 when 'caonaboalbero' then 9
  end;
  if legacy is null then return new; end if;
  visible_name := case uname
    when 'kike' then 'Kike' when 'lizzy' then 'Lizzy' when 'raul' then 'Raúl'
    when 'mario' then 'Mario' when 'miguelangel' then 'Miguel Ángel'
    when 'almudena' then 'Almudena' when 'carlos' then 'Carlos'
    when 'albertovelasco' then 'Alberto Velasco' when 'caonaboalbero' then 'Caonabo Albero'
  end;
  if uname = 'kike' then member_role := 'admin'; end if;
  insert into public.profiles (id, legacy_id, username, display_name, nickname, bio, tags, role)
  values (new.id, legacy, uname, visible_name, 'The Big Boy', 'Miembro de The Big Boy Rules.',
    array['Comunidad', 'Momentos', 'Grupo'], member_role)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_big_boy();
