-- Ejecutar una vez en Supabase SQL Editor.
alter table public.moments add column if not exists mentioned_user_id uuid references public.profiles(id) on delete set null;
alter table public.profile_posts add column if not exists mentioned_user_id uuid references public.profiles(id) on delete set null;
create table if not exists public.moment_views (
  id bigint generated by default as identity primary key,
  moment_id bigint not null references public.moments(id) on delete cascade,
  viewer_id uuid not null references auth.users(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  unique (moment_id, viewer_id)
);

create table if not exists public.media_replies (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  moment_id bigint references public.moments(id) on delete cascade,
  profile_post_id bigint references public.profile_posts(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 600),
  created_at timestamptz not null default now(),
  check ((moment_id is not null)::int + (profile_post_id is not null)::int = 1)
);

alter table public.moment_views enable row level security;
alter table public.media_replies enable row level security;

alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.notifications
  add constraint notifications_type_check
  check (type in ('private_message', 'like', 'reply', 'media_created'));

create policy "members register moment views" on public.moment_views
  for insert to authenticated with check (viewer_id = auth.uid());
create policy "members refresh own moment view" on public.moment_views
  for update to authenticated using (viewer_id = auth.uid()) with check (viewer_id = auth.uid());
create policy "owners read moment viewers" on public.moment_views
  for select to authenticated using (
    viewer_id = auth.uid() or exists (select 1 from public.moments m where m.id = moment_id and m.user_id = auth.uid())
  );

create policy "members create media replies" on public.media_replies
  for insert to authenticated with check (user_id = auth.uid());
create policy "participants read media replies" on public.media_replies
  for select to authenticated using (
    user_id = auth.uid()
    or exists (select 1 from public.moments m where m.id = moment_id and m.user_id = auth.uid())
    or exists (select 1 from public.profile_posts p where p.id = profile_post_id and p.user_id = auth.uid())
  );
create policy "members delete own replies" on public.media_replies
  for delete to authenticated using (user_id = auth.uid() or public.current_user_can_manage());

create or replace function public.notify_media_reply()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  recipient uuid;
begin
  if new.moment_id is not null then
    select user_id into recipient from public.moments where id = new.moment_id;
  else
    select user_id into recipient from public.profile_posts where id = new.profile_post_id;
  end if;

  if recipient is not null and recipient <> new.user_id then
    insert into public.notifications (user_id, actor_id, type, target_type, target_id, excerpt)
    values (
      recipient,
      new.user_id,
      'reply',
      case when new.moment_id is not null then 'moment' else 'post' end,
      coalesce(new.moment_id, new.profile_post_id),
      left(trim(new.body), 180)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists notify_media_reply on public.media_replies;
create trigger notify_media_reply
  after insert on public.media_replies
  for each row execute procedure public.notify_media_reply();

create index if not exists moment_views_moment_time_idx on public.moment_views(moment_id, viewed_at desc);
create index if not exists media_replies_moment_time_idx on public.media_replies(moment_id, created_at desc) where moment_id is not null;
create index if not exists media_replies_post_time_idx on public.media_replies(profile_post_id, created_at desc) where profile_post_id is not null;
create index if not exists media_likes_user_idx on public.media_likes(user_id);
create index if not exists moments_created_at_idx on public.moments(created_at desc);
create index if not exists profile_posts_created_at_idx on public.profile_posts(created_at desc);

-- Permite originales y vídeos de alta resolución de hasta 100 MB.
update storage.buckets set file_size_limit = 104857600 where id = 'group-media';

do $$ begin
  alter publication supabase_realtime add table public.media_replies;
exception when duplicate_object then null;
end $$;
