import {test, before, after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';

// Real PostgreSQL/PLpgSQL in memory. No access to production, credentials or network.
const db = new PGlite();
const admin='00000000-0000-0000-0000-000000000001';
const alice='00000000-0000-0000-0000-000000000002';
const bob='00000000-0000-0000-0000-000000000003';
const hidden='00000000-0000-0000-0000-000000000004';
const sql = file => readFile(new URL('../'+file,import.meta.url),'utf8');
const query = async (text, params=[]) => (await db.query(text,params)).rows;
async function asUser(id, fn) {
  await db.exec('set role authenticated');
  await query("select set_config('request.jwt.claim.sub', $1, false)",[id]);
  try { return await fn(); } finally { await db.exec('reset role'); }
}
const create = (metric,target,name='Objetivo de prueba') => asUser(admin, async () =>
  (await query('select public.create_automatic_achievement($1,$2,$3,$4,$5) as id',[name,'Descripción','gold',metric,target]))[0].id);
const send = (user,createdAt='2020-01-01') => asUser(user,()=>query('insert into public.messages(user_id,body,created_at) values ($1,$2,$3) returning id',[user,'Mensaje de prueba',createdAt]));
const progress = async (id,user) => (await query('select * from public.achievement_progress where achievement_id=$1 and user_id=$2',[id,user]))[0];
let messageRule,dayRule,profileRule;

before(async () => {
  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth, public to authenticated, anon;
    grant execute on function auth.uid() to authenticated, anon;
    -- Reproduce Supabase's broad default grants: the migration must revoke them explicitly.
    alter default privileges in schema public grant all on tables to authenticated, anon;
    alter default privileges in schema public grant all on sequences to authenticated, anon;
    alter default privileges in schema public grant execute on functions to authenticated, anon;
    create table public.profiles(id uuid primary key, display_name text, avatar_url text, bio text default '', role text default 'member', is_hidden boolean default false);
    create table public.messages(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id),body text,attachment_url text,created_at timestamptz default now(),check(length(trim(coalesce(body,'')))>0 or attachment_url is not null));
    create table public.private_messages(id bigint generated by default as identity primary key,sender_id uuid,recipient_id uuid,body text);
    alter table public.profiles enable row level security;
    create policy read_profiles on public.profiles for select to authenticated using(true);
    create policy edit_self on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
    alter table public.messages enable row level security;
    create policy read_messages on public.messages for select to authenticated using(true);
    create policy send_own on public.messages for insert to authenticated with check(user_id=auth.uid());
    create policy edit_own on public.messages for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
    create policy delete_own on public.messages for delete to authenticated using(user_id=auth.uid());
    create publication supabase_realtime;
    create table public.help_requests(id bigint primary key,user_id uuid);
    create table public.help_messages(id bigint,request_id bigint);
    create function public.current_user_is_help_admin() returns boolean language sql as $$ select false $$;
    insert into public.profiles(id,display_name,avatar_url,bio,role,is_hidden) values
      ('${admin}','Admin',null,'','admin',false),('${alice}','Alice',null,'','member',false),
      ('${bob}','Bob','https://example.test/avatar.png','Mi bio','member',false),('${hidden}','Oculto','https://example.test/hidden.png','Mi bio','member',true);
    insert into public.messages(user_id,body) values ('${alice}','Histórico');
  `);
  await db.exec(await sql('supabase-achievements.sql'));
  await db.exec(await sql('supabase-achievement-progress.sql'));
});
after(()=>db.close());

// Collection extension tests run after the original goals, on the same isolated DB.

test('only admins can create validated atomic objectives; invalid creation leaves no rows', async () => {
  await assert.rejects(asUser(alice,()=>query("select create_automatic_achievement('Hack','','gold','group_messages',1)")),/permiso/);
  const before=(await query('select count(*)::int as n from achievements'))[0].n;
  for (const [metric,target] of [['no_such_metric',1],['group_messages',0],['group_messages',100001],['profile_completed',2],['group_messages',null],[null,1]]) {
    await assert.rejects(create(metric,target));
  }
  assert.equal((await query('select count(*)::int as n from achievements'))[0].n,before);
  messageRule=await create('group_messages',3);
  dayRule=await create('group_active_days',3,'Días distintos');
  profileRule=await create('profile_completed',1,'Tu identidad');
  assert.equal(await progress(messageRule,alice),undefined,'historical messages do not count');
});

test('profile objective recognizes complete profiles once, excludes hidden and supports future members',async()=>{
  assert.equal((await progress(profileRule,bob)).current_value,1);
  assert.ok((await progress(profileRule,bob)).completed_at);
  assert.equal(await progress(profileRule,hidden),undefined);
  await asUser(alice,()=>query("update profiles set bio='Mi bio', avatar_url='https://example.test/a.png' where id=$1",[alice]));
  assert.equal((await progress(profileRule,alice)).current_value,1);
  await asUser(alice,()=>query("update profiles set bio='Otra bio' where id=$1",[alice]));
  assert.equal((await query('select count(*)::int as n from achievement_awards where achievement_id=$1 and user_id=$2',[profileRule,alice]))[0].n,1);
  const newcomer='00000000-0000-0000-0000-000000000005';
  await query("insert into profiles(id,display_name,avatar_url,bio) values($1,'Nuevo','https://example.test/new.png','Hola')",[newcomer]);
  assert.equal((await progress(profileRule,newcomer)).current_value,1);
});

test('messages advance only the sender; edits, deletion and reinsertion do not duplicate an event',async()=>{
  const [{id}]=await send(alice);
  assert.equal((await progress(messageRule,alice)).current_value,1);
  assert.equal(await progress(messageRule,bob),undefined);
  await asUser(alice,()=>query("update messages set body='Editado' where id=$1",[id]));
  assert.equal((await progress(messageRule,alice)).current_value,1);
  await asUser(alice,()=>query('delete from messages where id=$1',[id]));
  await asUser(alice,()=>query("insert into messages(id,user_id,body) values($1,$2,'Reintentado')",[id,alice]));
  assert.equal((await progress(messageRule,alice)).current_value,1);
  assert.equal(await progress(dayRule,alice),undefined,'writing is not an app login');
});

test('only one group message counts per day; visits count without messages and neither trusts client dates',async()=>{
  await send(alice,'2099-01-01');
  await send(alice,'1999-01-01');
  assert.equal((await progress(messageRule,alice)).current_value,1);
  assert.equal(await progress(dayRule,alice),undefined);
  for (let i=0;i<4;i++) await asUser(alice,()=>query('select record_daily_app_visit()'));
  await asUser(bob,()=>query('select record_daily_app_visit()'));
  assert.equal((await progress(dayRule,alice)).current_value,1,'several logins or devices today count once');
  assert.equal((await progress(dayRule,bob)).current_value,1,'no message required');
  assert.equal(await progress(messageRule,bob),undefined);
  // Simulate trusted server events on distinct days; clients cannot call this helper.
  await query("select record_achievement_activity($1,'group_messages','day:2026-01-01',$2)",[alice,messageRule]);
  await query("select record_achievement_activity($1,'group_messages','day:2026-01-02',$2)",[alice,messageRule]);
  assert.equal((await progress(messageRule,alice)).current_value,3);
  const first=(await progress(messageRule,alice)).completed_at;
  await send(alice);
  assert.equal((await progress(messageRule,alice)).current_value,3);
  assert.equal(String((await progress(messageRule,alice)).completed_at),String(first));
  assert.equal((await query('select count(*)::int as n from achievement_awards where achievement_id=$1 and user_id=$2',[messageRule,alice]))[0].n,1);
  assert.equal((await progress(dayRule,alice)).current_value,1);
  // Simulate the trusted trigger firing on other days, never through an authenticated RPC.
  await query("select record_achievement_activity($1,'group_active_days','day:2026-01-01',$2)",[alice,dayRule]);
  await query("select record_achievement_activity($1,'group_active_days','day:2026-01-01',$2)",[alice,dayRule]);
  assert.equal((await progress(dayRule,alice)).current_value,2);
  await query("select record_achievement_activity($1,'group_active_days','day:2026-01-09',$2)",[alice,dayRule]);
  assert.equal((await progress(dayRule,alice)).current_value,3,'days need not be consecutive');
});

test('private messages and hidden users do not advance group objectives',async()=>{
  await query("insert into private_messages(sender_id,recipient_id,body) values($1,$2,'Privado')",[bob,alice]);
  assert.equal(await progress(messageRule,bob),undefined);
  await send(hidden);
  assert.equal(await progress(messageRule,hidden),undefined);
});

test('rolled-back messages do not count; attachments count and new goals never inherit earlier activity',async()=>{
  await db.exec('begin');
  await query("insert into messages(user_id,body) values($1,'Se cancelará')",[bob]);
  assert.equal((await progress(messageRule,bob)).current_value,1);
  await db.exec('rollback');
  assert.equal(await progress(messageRule,bob),undefined);
  await asUser(bob,()=>query("insert into messages(user_id,body,attachment_url) values($1,'','https://example.test/audio.m4a')",[bob]));
  assert.equal((await progress(messageRule,bob)).current_value,1);
  const newGoal=await create('group_messages',50,'Una nueva etapa');
  assert.equal(await progress(newGoal,bob),undefined);
  await send(bob);
  assert.equal((await progress(newGoal,bob)).current_value,1);
  assert.equal((await progress(messageRule,bob)).current_value,1,'attachment and text share the same daily limit');
});

test('RLS exposes only own progress, even to administrators; ledger and counters cannot be forged',async()=>{
  await asUser(alice,async()=>{
    const rows=await query('select * from achievement_progress');
    assert.ok(rows.length>=3); assert.ok(rows.every(r=>r.user_id===alice));
    assert.equal((await query('select * from achievement_progress where user_id=$1',[bob])).length,0);
    await assert.rejects(query('select * from achievement_progress_events'),/permission denied/);
    await assert.rejects(query('update achievement_progress set current_value=999'),/permission denied/);
    await assert.rejects(query('delete from achievement_rules'),/permission denied/);
    await assert.rejects(query("select record_achievement_activity($1,'group_messages','forged',null)",[alice]),/permission denied/);
    await assert.rejects(query('select track_group_achievement_activity()'),/permission denied/);
    await assert.rejects(query('select record_daily_app_visit($1::uuid)',[bob]),/does not exist/);
    await assert.rejects(query("insert into messages(user_id,body) values($1,'Forged sender')",[bob]),/row-level security/);
  });
  assert.equal((await asUser(admin,()=>query('select * from achievement_progress'))).length,0);
  await db.exec('set role anon');
  try {
    await assert.rejects(query('select * from achievement_progress'),/permission denied/);
    await assert.rejects(query("select create_automatic_achievement('Hack','','gold','group_messages',1)"),/permission denied/);
    await assert.rejects(query('select record_daily_app_visit()'),/permission denied/);
  } finally { await db.exec('reset role'); }
});

test('automatic awards cannot be manually granted or revoked, including direct API calls',async()=>{
  await asUser(admin,async()=>{
    await assert.rejects(query('select set_achievement_awards($1,$2::uuid[])',[messageRule,[bob]]),/automáticamente/);
    await assert.rejects(query('insert into achievement_awards(achievement_id,user_id,awarded_by) values($1,$2,$3)',[messageRule,bob,admin]),/row-level security/);
    const deleted=await query('delete from achievement_awards where achievement_id=$1 returning id',[messageRule]);
    assert.equal(deleted.length,0);
  });
  assert.equal((await query('select count(*)::int as n from achievement_awards where achievement_id=$1',[messageRule]))[0].n,1);
});

test('manual creation and assignment still work; retained award dates are stable',async()=>{
  await asUser(admin,async()=>{
    const [{id}]=await query("select create_achievement_with_awards('Manual','','silver',null,$1::uuid[]) as id",[[alice]]);
    const [award]=await query('select * from achievement_awards where achievement_id=$1',[id]);
    await query('select set_achievement_awards($1,$2::uuid[])',[id,[alice,bob]]);
    const rows=await query('select * from achievement_awards where achievement_id=$1 order by user_id',[id]);
    assert.equal(rows.length,2); assert.equal(rows[0].id,award.id);
    assert.equal(String(rows[0].awarded_at),String(award.awarded_at));
    await query('select set_achievement_awards($1,$2::uuid[])',[id,[bob]]);
    assert.equal((await query('select * from achievement_awards where achievement_id=$1',[id])).length,1);
  });
});

test('reapplying migration preserves earned progress and deleting an objective cleans up its own rows',async()=>{
  const before=await progress(messageRule,alice);
  await db.exec(await sql('supabase-achievement-progress.sql'));
  assert.equal((await progress(messageRule,alice)).current_value,before.current_value);
  await asUser(admin,()=>query('delete from achievements where id=$1',[dayRule]));
  for (const table of ['achievement_rules','achievement_progress','achievement_progress_events','achievement_awards']) {
    assert.equal((await query(`select * from ${table} where achievement_id=$1`,[dayRule])).length,0);
  }
  assert.ok(await progress(messageRule,alice),'other trophies survive');
});

test('collection migration adds validated goals without changing earlier trophies',async()=>{
  const previous=await progress(messageRule,alice);
  await db.exec(await sql('supabase-daily-packs.sql'));
  await db.exec(await sql('supabase-collection-achievements.sql'));
  await db.exec(await sql('supabase-collection-achievements.sql'));
  assert.equal((await progress(messageRule,alice)).current_value,previous.current_value);
  await assert.rejects(create('cards_explored',14),/supera/);
  await assert.rejects(create('special_cards_explored',2),/supera/);
  await assert.rejects(create('legendary_cards_explored',2),/supera/);
  await assert.rejects(create('locations_explored',3),/supera/);
  await assert.rejects(asUser(alice,()=>query("select create_automatic_achievement('Hack','','gold','cards_explored',1)")),/permiso/);
});

test('card exploration counts distinct IDs, correct rarities and only the acting user',async()=>{
  const cards=await create('cards_explored',3), special=await create('special_cards_explored',1);
  const legendary=await create('legendary_cards_explored',1), places=await create('locations_explored',2);
  const explore=id=>asUser(alice,()=>query('select record_card_exploration($1) as changed',[id]));
  await explore('jose-enrique-fernandez-cruz-normal');
  assert.equal((await progress(cards,alice)).current_value,1);
  assert.equal((await explore('jose-enrique-fernandez-cruz-normal'))[0].changed,false);
  assert.equal(await progress(places,alice),undefined);
  assert.equal(await progress(special,alice),undefined);
  await explore('luca-de-tena-especial');
  assert.equal((await progress(cards,alice)).current_value,2);
  assert.ok((await progress(special,alice)).completed_at);
  assert.equal(await progress(legendary,alice),undefined);
  await explore('borox-legendaria');
  assert.equal((await progress(cards,alice)).current_value,3);
  assert.ok((await progress(legendary,alice)).completed_at);
  assert.equal((await progress(places,alice)).current_value,2);
  assert.equal(await progress(cards,bob),undefined);
  for(let i=0;i<5;i++) await explore('borox-legendaria');
  assert.equal((await query('select count(*)::int as n from achievement_awards where achievement_id=$1 and user_id=$2',[cards,alice]))[0].n,1);
  const fresh=await create('cards_explored',1);
  assert.equal(await progress(fresh,alice),undefined,'no historical catalog exploration imported');
  await explore('borox-legendaria');
  assert.ok((await progress(fresh,alice)).completed_at,'a new objective can count a new exploration of an existing card');
});

test('pack progress uses real daily credits, not balance refresh, preview, edits or other users',async()=>{
  await asUser(bob,()=>query('select claim_daily_card_pack()'));
  const goal=await create('daily_packs_earned',2);
  assert.equal(await progress(goal,bob),undefined,'old packs do not backfill');
  for(let i=0;i<4;i++) await asUser(alice,()=>query('select claim_daily_card_pack()'));
  assert.equal((await progress(goal,alice)).current_value,1);
  await asUser(bob,()=>query('select claim_daily_card_pack()'));
  assert.equal(await progress(goal,bob),undefined);
  await query('update card_packs set opened_at=now() where user_id=$1',[alice]);
  assert.equal((await progress(goal,alice)).current_value,1);
  await db.exec('begin');
  await query("insert into card_packs(user_id,earned_day) values($1,'2098-01-01')",[alice]);
  assert.ok((await progress(goal,alice)).completed_at);
  await db.exec('rollback');
  assert.equal((await progress(goal,alice)).current_value,1);
  await query("insert into card_packs(user_id,earned_day) values($1,'2098-01-02')",[alice]);
  assert.ok((await progress(goal,alice)).completed_at);
});

test('collection counters and metadata cannot be forged through authenticated table writes',async()=>{
  const goal=await create('cards_explored',1);
  await asUser(alice,async()=>{
    await assert.rejects(query("select record_card_exploration('invented-card')"),/no está disponible/);
    await assert.rejects(query("update achievement_card_catalog set edition='legendary'"),/permission denied/);
    await assert.rejects(query("insert into card_packs(user_id,earned_day) values($1,'2099-01-01')",[alice]),/permission denied/);
    await assert.rejects(query('select track_daily_pack_achievement()'),/permission denied/);
    await assert.rejects(query("select record_achievement_activity($1,'daily_packs_earned','fake',null)",[alice]),/permission denied/);
    await assert.rejects(query("select record_card_exploration('borox-legendaria',$1::uuid)",[bob]),/does not exist/);
  });
  await asUser(hidden,()=>query("select record_card_exploration('borox-legendaria')"));
  assert.equal(await progress(goal,hidden),undefined);
  await db.exec('set role anon');
  try { await assert.rejects(query("select record_card_exploration('borox-legendaria')"),/permission denied/); }
  finally { await db.exec('reset role'); }
  const before=await query('select count(*)::int as n from achievement_awards');
  await db.exec(await sql('supabase-collection-achievements.sql'));
  assert.deepEqual(await query('select count(*)::int as n from achievement_awards'),before);
});
